local ust = require "ust"

local fitModels = {
    surface = ust.fitModel(4.4, 5, -2, true, true),
    edge = ust.fitModel(0.3, 5, -2, true, true),
}

-- e : extremity
-- i : intermediate
-- t : terminal side
-- x : cross section
local fitMdl = {
    ["xe_ye_left"] = fitModels.edge,
    ["xe_ye_right"] = fitModels.edge,
    ["xe_yi_left"] = fitModels.edge,
    ["xe_yi_right"] = fitModels.edge,
    ["xi_ye_left"] = fitModels.edge,
    ["xi_ye_left_t"] = fitModels.edge,
    ["xi_ye_right"] = fitModels.edge,
    ["xi_ye_right_t"] = fitModels.edge,
    ["xi_yi_left"] = fitModels.edge,
    ["xi_yi_left_x"] = fitModels.edge,
    ["xi_yi_right"] = fitModels.edge,
    ["xi_yi_right_x"] = fitModels.edge,
    ["ye_centre"] = fitModels.surface,
    ["ye_centre_t"] = fitModels.surface,
    ["yi_centre"] = fitModels.surface,
}

local config = {
    edgeWidth = 0.3,
    path = "ust/platform/era_b/",
    laneMdl = "ust/terminal_lane.mdl",
    fitMdl = fitMdl
}

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    game.res.script["construction/station/rail/ust/struct/platform"].updateFn(result, transform, tag, slotId, addModelFn, params, config)
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_PLATFORM"),
            description = _("MENU_MODULE_PLATFORM_DESC"),
        },
        category = {
            categories = {"ust_cat_platform"},
        },
        type = "ust_platform",
        order = {
            value = 4,
        },
        metadata = {
            typeName = "ust_platform",
            isPlatform = true,
            typeId = 2,
            width = 5,
            scriptName = "construction/station/rail/ust/struct/platform",
            preProcessAdd = "preProcessAdd",
            preProcessRemove = "preProcessRemove",
            slotSetup = "slotSetup",
            preClassify = "preClassify",
            postClassify = "postClassify",
            gridization = "gridization"
        },
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
