local coor = require "ust/coor"
local quat = require "ust/quaternion"
local ust = require "ust"

local insert = table.insert
local ma = math
local pi = ma.pi

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local id = params.modules[slotId].info.id
    local sId = params.classedModules[id].slotId
    local info = params.modules[sId].info
    local isPlatform = params.modules[sId].metadata.isPlatform
    local isTrack = params.modules[sId].metadata.isTrack
    local refH = info.height
    local makeData = params.modules[sId].makeData
    
    insert(result.slots, {
        id = makeData(91, 1),
        transf = info.transf * coor.transZ(refH),
        type = "ust_ref_modifier",
        spacing = {0, 0, 0, 0}
    })
    
    local n = 2
    local ptsL, vecL = ust.basePts(info.arcs.left, n)
    local ptsR, vecR = ust.basePts(info.arcs.right, n)
    local ptsC, vecC = ust.basePts(info.arcs.center, n)
    
    local addSlot = function(cond, data, transf)
        if cond then
            insert(result.slots, {
                id = makeData(92, data),
                transf = coor.scale(coor.xyz(0.125, 0.5, 1)) * coor.rotZ(-0.25 * pi) * transf * coor.transZ(refH),
                type = "ust_ref_modifier",
                spacing = {0, 0, 0, 0},
                shape = 2
            })
            
            insert(result.slots, {
                id = makeData(92, data),
                transf = coor.scale(coor.xyz(0.125, 0.5, 1)) * coor.rotZ(0.25 * pi) * transf * coor.transZ(refH),
                type = "ust_ref_modifier",
                spacing = {0, 0, 0, 0},
                shape = 2
            })
        else
            insert(result.slots, {
                id = makeData(92, data),
                transf = transf * coor.transZ(refH),
                type = "ust_ref_modifier",
                spacing = {0, 0, 0, 0},
                shape = 1
            })
        end
    end
    
    if params.debug ~= 1 then
        ust.marking(result, slotId, params)
        
        for _, octa in ipairs(info.octa) do
            if octa then
                ust.marking(result, octa, params)
            end
        end
    end
    
    if isPlatform then
        local m7 = info.octa[7] and params.modules[info.octa[7]] or nil
        local m3 = info.octa[3] and params.modules[info.octa[3]] or nil

        local refPt = ptsL[2]
        local refVec = vecL[2]
        local transf = quat.byVec(coor.xyz(0, 1, 0), refVec):mRot() * coor.trans(refPt)
        if m7 and not (
            (m7.metadata.isPlatform and m7.info.ref.right) 
            or (m7.metadata.isTrack and m7.info.ref.right and not info.ref.right)
            or (m7.metadata.isTrack and m3.info.ref.left and m7.info.ref.right)
            or (m7.metadata.isTrack and m3.info.ref.left and info.ref.left and info.ref.right)
        ) then
            local sum = (info.ref.right and 2 or 0) + (info.ref.left and 0 or 1)
            if (sum ~= 0) then
                addSlot(info.ref.left, sum, transf)
            end
        end
        
        local refPt = ptsR[2]
        local refVec = vecR[2]
        local transf = quat.byVec(coor.xyz(0, -1, 0), refVec):mRot() * coor.trans(refPt)
        
        if m3 and not (
            (m3.metadata.isPlatform and m3.info.ref.left) 
            or (m3.metadata.isTrack and m3.info.ref.left and not info.ref.left)
            or (m3.metadata.isTrack and m7.info.ref.right and m3.info.ref.left)
            or (m3.metadata.isTrack and m7.info.ref.right and info.ref.left and info.ref.right)
        ) then
            local sum = (info.ref.left and 1 or 0) + (info.ref.right and 0 or 2)
            if sum ~= 0 then
                addSlot(info.ref.right, sum, transf)
            end
        end
    end
    
    if isTrack then
        local refPt = ptsL[2]
        local refVec = vecL[2]
        local transf = quat.byVec(coor.xyz(0, 1, 0), refVec):mRot() * coor.trans(refPt)
        
        if (info.octa[7] and params.modules[info.octa[7]] and not params.modules[info.octa[7]].info.ref.right) then
            if info.ref.left then
                addSlot(true, 0, transf)
            else
                addSlot(false, 1, transf)
            end
        end
    
        local refPt = ptsR[2]
        local refVec = vecR[2]
        local transf = quat.byVec(coor.xyz(0, -1, 0), refVec):mRot() * coor.trans(refPt)
        
        if (info.octa[3] and params.modules[info.octa[3]] and not params.modules[info.octa[3]].info.ref.left) then
            if info.ref.right then
                addSlot(true, 0, transf)
            else
                addSlot(false, 2, transf)
            end
        end
    end
    
    do
        local i = 3
        local refPt = ptsC[i]
        local refVec = vecC[i]
        local transf = quat.byVec(coor.xyz(-1, 0, 0), refVec):mRot() * coor.trans(refPt)
        
        if info.octa[1] and params.modules[info.octa[1]] and not params.modules[info.octa[1]].info.ref.prev then
            if not info.ref.next then
                addSlot(info.ref.next, 4, transf)
            end
        end
    
    end
    
    do
        local i = 1
        local refPt = ptsC[i]
        local refVec = vecC[i]
        local transf = quat.byVec(coor.xyz(1, 0, 0), refVec):mRot() * coor.trans(refPt)
        
        if info.octa[5] and params.modules[info.octa[5]] and not params.modules[info.octa[5]].info.ref.next then
            if not info.ref.prev then
                addSlot(info.ref.prev, 8, transf)
            end
        end
    end
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        visible = false,
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_REF_MODIFIER"),
            description = _("MENU_REF_MODIFIER_DESC"),
        },
        category = {
            categories = {"ust_cat_modifier"},
        },
        type = "ust_ref_modifier",
        order = {
            value = 1,
        },
        metadata = {
            typeName = "ust_ref_modifier",
            isData = true,
            type = 92,
            scriptName = "construction/station/rail/ust/modifier/ref",
            preProcessAdd = "preProcessAdd",
            preProcessPostAdd = "preProcessPostAdd",
            classify = "classify"
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
