local insert = table.insert
local coor = require "ust/coor"

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local info = params.modules[slotId].info
    local trackSlotId = params.classedModules[info.id].slotId
    local module = params.modules[trackSlotId]
    local makeData = params.modules[params.classedModules[info.id].slotId].makeData
    
    insert(result.slots, {
        id = makeData(27, -2),
        transf = coor.scale(coor.xyz(1, 0.1, 1)) * coor.rotZ(0.25 * math.pi) * module.info.transf,
        type = "ust_tram",
        spacing = {0, 0, 0, 0}
    })
    insert(result.slots, {
        id = makeData(27, -2),
        transf = coor.scale(coor.xyz(1, 0.1, 1)) * coor.rotZ(-0.25 * math.pi) * module.info.transf,
        type = "ust_tram",
        spacing = {0, 0, 0, 0}
    })
    
    if module.metadata.isStreet then
        module.info.tramTrack = true
        insert(result.invokeLater, function()
            local trackEdgeIndex = params.edgeIndex[trackSlotId][5]
            local trackEdges = result.edgeLists[trackEdgeIndex]
            if trackEdges then
                trackEdges.params.tramTrackType = "YES"
            end
            if result.edgeLists[trackEdgeIndex + 1] and result.edgeLists[trackEdgeIndex + 1].slot == trackSlotId then
                local trackEdges = result.edgeLists[trackEdgeIndex + 1]
                if trackEdges then
                    trackEdges.params.tramTrackType = "YES"
                end
            end
        end)
    end
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_CATENARY"),
            description = _("MENU_MODULE_CATENARY_DESC"),
        },
        category = {
            categories = {"ust_cat_comp"},
        },
        type = "ust_tram",
        order = {
            value = 1,
        },
        metadata = {
            typeName = "ust_tram",
            typeId = 27,
            scriptName = "construction/station/rail/ust/struct/tram",
            preProcessAdd = "preProcessAdd",
            addSlot = "addSlot",
            classify = "classify"
        },
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end