local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    game.res.script["construction/station/rail/ust/struct/street"].updateFn(result, transform, tag, slotId, addModelFn, params, "asphalt")
end

function data()
    return {
        availability = {
            yearFrom = 1925,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_STREET_ASPHALT"),
            description = _("MENU_MODULE_STREET_ASPHALT_DESC"),
        },
        category = {
            categories = {"ust_cat_street"},
        },
        type = "ust_street",
        order = {
            value = 11,
        },
        metadata = {
            typeName = "ust_street",
            isStreet = true,
            width = 3.5,
            height = 0,
            typeId = 4,
            scriptName = "construction/station/rail/ust/struct/street",
            preProcessAdd = "preProcessAdd",
            preProcessRemove = "preProcessRemove",
            slotSetup = "slotSetup",
            preClassify = "preClassify",
            postClassify = "postClassify",
            gridization = "gridization"
        },
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }
end
