local config = {
    width = 2.5,
    pole = "ust/fences/green/pole_2.mdl",
    fence = "ust/fences/green/fence_2.mdl",
}

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    game.res.script["construction/station/rail/ust/struct/fence"].updateFn(result, transform, tag, slotId, addModelFn, params, config)
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_FENCE_GREEN"),
            description = _("MENU_MODULE_FENCE_GREEN_DESC"),
        },
        category = {
            categories = {"ust_cat_comp"},
        },
        type = "ust_component_fence",
        order = {
            value = 260,
        },
        metadata = {
            scriptName = "construction/station/rail/ust/struct/fence",
            classify = "classify",
            typeName = "ust_component_fence",
            isComponent = true,
            isFence = true,
            typeId = 24,
            width = 5
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
