local coor = require "ust/coor"
local ust = require "ust"

--Begin Generated
local generatedData = {
    ["assets"] = {
        ["station/rail/asset/era_c_street_pillar.mdl"] = {
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -5.00000, -16.30000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -3.00000, -16.30000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, -11.05000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -1.00000, -16.30000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 1.00000, -16.30000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 2.50000, -11.05000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, -2.50000, -11.05000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 3.00000, -16.30000, 0.00000, 1.00000},
            {1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000, 0.00000, 1.00000, 0.00000, 5.00000, -16.30000, 0.00000, 1.00000},
        },
    },
}
--End Generated

local fitModels = {
    surface = ust.fitModel(3.3, 5, -2, true, true),
    edge = ust.fitModel(0.85, 5, -2, true, true),
}

local fitMdl = {
    ["xe_yi_left"] = fitModels.edge,
    ["xe_yi_right"] = fitModels.edge,
    ["yi_centre"] = fitModels.surface,
    ["ye_centre"] = fitModels.surface,
    ["xe_ye_left"] = fitModels.edge,
    ["xe_ye_right"] = fitModels.edge,
}

local mdls = {
    extend = {6, -6, 0, -17, 4, 0},
    main = "ust/main_buildings/station_1.mdl",
    end_left = "ust/main_buildings/station_1_end_l.mdl",
    end_right = "ust/main_buildings/station_1_end_r.mdl",
}

local config = {
    width = 10,
    extend = {6, -6, 0, -17, 4, 0},
    generatedData = generatedData,
    mdlList = {
        mdls.end_left,
        mdls.end_right,
        mdls.main
    },
    connectors = {
        coor.xyz(0, -2.5, 0),
    },
    fitMdl = fitMdl,
    edgeWidth = 0.85,
    depth = 5,
    path = "ust/platform/era_c/"
}

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    game.res.script["construction/station/rail/ust/struct/building"].updateFn(result, transform, tag, slotId, addModelFn, params, config)
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_SIDE_ENTRY_10"),
            description = _("MENU_MODULE_SIDE_ENTRY_10_DESC"),
            icon = "ui/construction/station/rail/modular_station/side_building_1_era_c.tga"
        },
        category = {
            categories = {"ust_cat_entry"},
        },
        type = "ust_component_main_10",
        order = {
            value = 32,
        },
        metadata = {
            scriptName = "construction/station/rail/ust/struct/building",
            classify = "classify",
            typeName = "ust_component_main_10",
            isComponent = true,
            isBuilding = true,
            typeId = 31,
            moreCapacity = {
                passenger = 20
            }
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
