local coor = require "ust/coor"
local quat = require "ust/quaternion"
local ust = require "ust"

local insert = table.insert

local fitModels = {
    edge = ust.fitModel(0.27, 5, 7, true, true),
    block = ust.fitModel(1.98, 5, 7, true, true),
    center = ust.fitModel(0.5, 5, 7, true, true),
}

local roofFitModels = {
    fitModels.edge,
    fitModels.block,
    fitModels.center,
    fitModels.block,
    fitModels.edge
}

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local id = params.modules[slotId].info.id
    local module = params.modules[params.classedModules[id].slotId]
    local info = module.info
    local makeData = module.makeData
    
    local n = 4
    local leftPts = ust.basePts(info.arcs.left, n)
    local rightPts = ust.basePts(info.arcs.right, n)
    local centerPts = ust.basePts(info.arcs.center, n)
    
    local isFirst = not (info.octa[1] and params.modules[info.octa[1]].info.comp[28])
    local isLast = not (info.octa[5] and params.modules[info.octa[5]].info.comp[28])
    
    local edges = {
        {}, {}, {}, {}, {}, {}, {}
    }
    
    for i = 1, n + 1 do
        local vec = (leftPts[i] - rightPts[i]):normalized()
        edges[1][i] = leftPts[i]
        edges[6][i] = rightPts[i]
        
        edges[2][i] = leftPts[i] - vec * 0.27
        edges[5][i] = rightPts[i] + vec * 0.27
        
        edges[7][i] = centerPts[i]
        edges[3][i] = centerPts[i] + vec * 0.25
        edges[4][i] = centerPts[i] - vec * 0.25
        
        for k = 1, 7 do
            edges[k][i] = edges[k][i]
        end
    end
    
    
    for i = 1, n do
        for k = 1, 5 do
            local coords = {
                lt = edges[k][i + 1],
                lb = edges[k][i],
                rt = edges[k + 1][i + 1],
                rb = edges[k + 1][i]
            }
            
            if isFirst and i == n then
                insert(result.models, ust.newModel(string.format("ust/platform/era_c/roof_end_%d_br.mdl", 6 - k), tag, coor.flipX() * coor.flipY() * roofFitModels[k](coords, true)));
                insert(result.models, ust.newModel(string.format("ust/platform/era_c/roof_end_%d_tl.mdl", 6 - k), tag, coor.flipX() * coor.flipY() * roofFitModels[k](coords, false)));
            elseif isLast and i == 1 then
                insert(result.models, ust.newModel(string.format("ust/platform/era_c/roof_end_%d_tl.mdl", k), tag, roofFitModels[k](coords, true)));
                insert(result.models, ust.newModel(string.format("ust/platform/era_c/roof_end_%d_br.mdl", k), tag, roofFitModels[k](coords, false)));
            else
                insert(result.models, ust.newModel(string.format("ust/platform/era_c/roof_%d_tl.mdl", k), tag, roofFitModels[k](coords, true)));
                insert(result.models, ust.newModel(string.format("ust/platform/era_c/roof_%d_br.mdl", k), tag, roofFitModels[k](coords, false)));
            end
        end
        
        if i % 2 == 1 then
            local vec = (edges[1][i + 1] - edges[6][i + 1]):normalized()
            local pos = edges[7][i + 1]
            
            local transf = quat.byVec(coor.xyz(1, 0, 0), vec):mRot() * coor.trans(pos)
            insert(result.models, ust.newModel("ust/platform/era_c/pole.mdl", tag, transf));
            insert(result.models, ust.newModel("ust/platform/era_c/arm.mdl", tag, transf));
            
            if i % 4 == 1 then
                local m3 = module.info.octa[3] and (params.modules[module.info.octa[3]].metadata.isTrack or params.modules[module.info.octa[3]].metadata.isStreet) or false
                local m7 = module.info.octa[7] and (params.modules[module.info.octa[7]].metadata.isTrack or params.modules[module.info.octa[7]].metadata.isStreet) or false
                if m3 or m7 then
                    local number3 = m3 and tostring(params.modules[module.info.octa[3]].info.trackGroup.left) or ""
                    local number7 = m7 and tostring(params.modules[module.info.octa[7]].info.trackGroup.right) or ""
                    result.labelText[#result.models] = {
                        number7, number7,
                        number3, number3
                    }
                    insert(result.models, ust.newModel("station/rail/asset/era_c_perron_number.mdl", tag, coor.transZ(2.5) * coor.rotZ90N * transf));
                end
            else
                insert(result.models, ust.newModel("station/rail/asset/era_c_perron_holder.mdl", tag, coor.transZ(2.5) * coor.rotZ90N * transf));
                insert(result.models, ust.newModel("station/rail/asset/era_c_small_clock.mdl", tag, coor.trans(coor.xyz(1.16, 0.25, 2.5)) * transf));
                insert(result.models, ust.newModel("station/rail/asset/era_c_small_clock.mdl", tag, coor.trans(coor.xyz(-1.16, 0.25, 2.5)) * transf));
            end
        end
    
    end
    insert(result.models, ust.newModel("station/rail/asset/era_c_station_name.mdl", tag, coor.transZ(2.3) * coor.rotZ90P * module.info.transf));
    
    -- SLot to replace itself
    insert(result.slots, {
        id = makeData(28, -1),
        transf = module.info.transf,
        type = "ust_roof",
        spacing = {0, 0, 0, 0}
    })
end
function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_PLATFORM_ROOF"),
            description = _("MENU_MODULE_PLATFORM_ROOF_DESC"),
        },
        category = {
            categories = {"ust_cat_comp"},
        },
        type = "ust_roof",
        order = {
            value = 302,
        },
        metadata = {
            scriptName = "construction/station/rail/ust/struct/roof",
            classify = "classify",
            typeName = "ust_roof",
            isRoof = true,
            isComponent = true,
            typeId = 28,
            width = 5
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
