local coor = require "ust/coor"
local quat = require "ust/quaternion"
local ust = require "ust"

local insert = table.insert

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local data = params.modules[slotId].info.data
    
    if data < 10 then
        insert(result.models, ust.newModel("station/rail/asset/era_c_double_chair.mdl", tag, transform))
    elseif data < 20 then
        insert(result.models, ust.newModel("station/rail/asset/era_c_single_chair.mdl", tag, coor.transX(-0.5) * transform))
    else
        insert(result.models, ust.newModel("station/rail/asset/era_c_single_chair.mdl", tag, coor.transX(-0.5) * coor.rotZ180 * transform))
    end
end
function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_PLATFORM_SEATS"),
            description = _("MENU_MODULE_PLATFORM_SEATS_DESC"),
        },
        category = {
            categories = {"ust_cat_comp"},
        },
        type = "ust_component_general",
        order = {
            value = 310,
        },
        metadata = {
            scriptName = "construction/station/rail/ust/struct/comp",
            classify = "classify",
            typeName = "ust_component_general",
            isComponent = true,
            typeId = 40,
            width = 5
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
