local coor = require "ust/coor"
local quat = require "ust/quaternion"
local ust = require "ust"

local insert = table.insert

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local id = params.modules[slotId].info.id
    local module = params.modules[params.classedModules[id].slotId]
    local info = module.info
    local makeData = module.makeData
    
    local hVec = coor.xyz(0, 0, info.height)
    local hTrans = coor.trans(hVec)
    
    local n = 4
    local centerPts, vecs = ust.basePts(info.arcs.center, n)
    
    for i = 1, n do
        if i % 2 == 1 then
            local pos = centerPts[i + 1] + hVec
            local transf = quat.byVec(coor.xyz(0, -1, 0), vecs[i + 1]):mRot() * coor.trans(pos)
            
            if i % 4 == 1 then
                local m3 = module.info.octa[3] and (params.modules[module.info.octa[3]].metadata.isTrack or params.modules[module.info.octa[3]].metadata.isStreet) or false
                local m7 = module.info.octa[7] and (params.modules[module.info.octa[7]].metadata.isTrack or params.modules[module.info.octa[7]].metadata.isStreet) or false
                if m3 or m7 then
                    local number3 = m3 and tostring(params.modules[module.info.octa[3]].info.trackGroup.left) or ""
                    local number7 = m7 and tostring(params.modules[module.info.octa[7]].info.trackGroup.right) or ""
                    result.labelText[#result.models] = {
                        number7, number7,
                        number3, number3
                    }
                    insert(result.models, ust.newModel("station/rail/asset/era_c_perron_number.mdl", tag, coor.transZ(2.5) * coor.rotZ90N * transf));
                    insert(result.models, ust.newModel("station/rail/asset/era_c_perron_pillar.mdl", tag, transf));
                end
            else
                insert(result.models, ust.newModel("station/rail/asset/era_c_perron_pillar.mdl", tag, transf));
                insert(result.models, ust.newModel("station/rail/asset/era_c_station_name.mdl", tag, coor.transZ(2.5) * coor.rotZ90P * transf));
                insert(result.models, ust.newModel("station/rail/asset/era_c_perron_holder.mdl", tag, coor.transZ(2.5) * coor.rotZ90N * transf));
                insert(result.models, ust.newModel("station/rail/asset/era_c_small_clock.mdl", tag, coor.trans(coor.xyz(1.16, 0.25, 2.5)) * transf));
                insert(result.models, ust.newModel("station/rail/asset/era_c_small_clock.mdl", tag, coor.trans(coor.xyz(-1.16, 0.25, 2.5)) * transf));
            end
        end
    end
    
    -- SLot to replace itself
    insert(result.slots, {
        id = makeData(28, -1),
        transf = module.info.transf * hTrans,
        type = "ust_roof",
        spacing = {0, 0, 0, 0}
    })
end
function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_PLATFORM_SIGN"),
            description = _("MENU_MODULE_PLATFORM_SIGN_DESC"),
        },
        category = {
            categories = {"ust_cat_comp"},
        },
        type = "ust_roof",
        order = {
            value = 3,
        },
        metadata = {
            scriptName = "construction/station/rail/ust/struct/roof",
            classify = "classify",
            typeName = "ust_roof",
            isComponent = true,
            typeId = 28,
            width = 5
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
