local coor = require "ust/coor"
local ust = require "ust"
local general = require "ust/general"

local insert = table.insert

local fitModels = ust.fitModel(0.5, 5, 5, true, true)


local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local id = params.modules[slotId].info.id
    local info = params.modules[params.classedModules[id].slotId].info
    local extraHeight = info.extraHeight or 0
    local isPlatform = params.modules[params.classedModules[id].slotId].metadata.isPlatform
    local baseHeight = (isPlatform and params.platformHeight or 0) + extraHeight
    local data = params.modules[slotId].info.data

    local hTrans = coor.transZ(baseHeight)
    
    if data == 3 or data == 7 then
        local h = 3
        local sideModule = info.octa[data] and params.modules[info.octa[data]]
        if sideModule then
            local info = sideModule.info
            local extraHeight = info.extraHeight or 0
            local isPlatform = sideModule.metadata.isPlatform
            local sideHeight = (isPlatform and params.platformHeight or 0) + extraHeight
            if sideHeight - baseHeight > 3 then
                h = sideHeight - baseHeight
            end
        end
        local n = 4
        local cpts = ust.basePts(info.arcs.center, n)
        local pts = ust.basePts(data == 3 and info.arcs.right or info.arcs.left, n)
        
        for i = 1, n do
            local coords = {
                rt = pts[i],
                rb = pts[i + 1],
                lt = (cpts[i] - pts[i]):normalized() * 0.5 + pts[i],
                lb = (cpts[i + 1] - pts[i + 1]):normalized() * 0.5 + pts[i + 1]
            }
            
            insert(result.models, general.newModel("ust/walls/concrete_wall_tl.mdl", tag, coor.scaleZ(h) * hTrans * fitModels(coords, true)))
            insert(result.models, general.newModel("ust/walls/concrete_wall_br.mdl", tag, coor.scaleZ(h) * hTrans * fitModels(coords, false)))
        end
    end

end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_WALL_CONCRETE"),
            description = _("MENU_MODULE_WALL_CONCRETE_DESC"),
        },
        category = {
            categories = {"ust_cat_comp"},
        },
        type = "ust_component_fence",
        order = {
            value = 260,
        },
        metadata = {
            scriptName = "construction/station/rail/ust/era_c/fence",
            classify = "classify",
            typeName = "ust_component_fence",
            isComponent = true,
            isFence = true,
            typeId = 24,
            width = 5
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
