local coor = require "ust/coor"
local quat = require "ust/quaternion"
local livetext = require "ust/livetext"

local ma = math
local pi = ma.pi

local updateFn = function(result, transform, tag, slotId, addModelFn, params)    
    local info = params.modules[slotId].info

    if params.debug then
        local text = tostring(info.id)
        local pos = string.format("(%d, %d)", info.pos.x, info.pos.y)
        
        local addText = function(label, pos, fAlign, h)
            local nameModelsF, width = livetext(h or 2)(label)
            for _, m in ipairs(nameModelsF(function() return coor.trans(fAlign(width)) * coor.rotX(-0.5 * pi) * quat.byVec(coor.xyz(0, info.pos.y < 0 and -1 or 1, 0), info.gravity[2]):mRot() * coor.trans(pos + coor.xyz(0, 0, 3)) end)) do
                table.insert(result.models, m)
            end
        end
        
        addText(text, info.gravity[1], function(w) return coor.xyz(-0.5 * w, 0, 0) end)
        addText(pos, info.gravity[1], function(w) return coor.xyz(-0.5 * w, 0, -2) end, 0.75)
    end
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_MODULE_PLATFORM_PLACEHOLDER"),
            description = _("MENU_MODULE_PLATFORM_PLACEHOLDER_DESC"),
        },
        category = {
            categories = {"ust_cat_helper"},
        },
        type = "ust_placeholder",
        order = {
            value = 260,
        },
        metadata = {
            typeName = "ust_placeholder",
            isPlaceholder = true,
            typeId = 3,
            width = 5,
            scriptName = "construction/station/rail/ust/era_c/platform",
            preProcessAdd = "preProcessAdd",
            slotSetup = "slotSetup",
            preClassify = "preClassify",
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
