local coor = require "ust/coor"
local quat = require "ust/quaternion"
local livetext = require "ust/livetext"
local ust = require "ust"

local unpack = table.unpack
local insert = table.insert
local ma = math
local pi = ma.pi
local abs = ma.abs
local pow = math.pow
local floor = math.floor

local preUpdateFn = function(modules, change, classedModules, info, data)
    if info.type == 80 and data == 1 then
        modules[ust.base(info.id, 80)] = nil
    elseif info.type == 80 and data == 0 then
        modules[ust.base(info.id, 80)] = change.module
    elseif info.type >= 81 and info.type <= 86 then
        ust.gridization(modules, classedModules)
        local id = info.id
        local m = modules[classedModules[id].slotId]
        
        if classedModules[id].slot[54] then
            modules[classedModules[id].slot[54]] = nil
        end
        
        if classedModules[id].slot[55] then
            modules[classedModules[id].slot[55]] = nil
        end
        
        if classedModules[id].slot[56] then
            modules[classedModules[id].slot[56]] = nil
        end
        
        modules[classedModules[id].slot[80]].variant = 1 - modules[classedModules[id].slot[80]].variant
        
        if info.type >= 81 and info.type <= 84 then
            local radius = m.info.radius
            
            local delta = data > 0 and pow(10, data - 1) or -pow(10, -data - 1)
            if m.info.radius == 10e8 or m.info.straight then
                radius = delta
            else
                radius = radius + delta
            end
            
            if radius > 999999 then radius = 999999 elseif radius < -999999 then radius = -999999 end
            
            local addSlot = ust.mixData(ust.base(id, 54), radius > 0 and radius % 1000 or -(-radius % 1000))
            modules[addSlot] = {
                metadata = {isData = true},
                name = "station/rail/ust/data.module",
                updateScript = {
                    fileName = "",
                    params = {}
                },
                variant = 0
            }
            
            local addSlot = ust.mixData(ust.base(id, 55), radius > 0 and floor(radius / 1000) or -(floor(-radius / 1000)))
            modules[addSlot] = {
                metadata = {isData = true},
                name = "station/rail/ust/data.module",
                updateScript = {
                    fileName = "",
                    params = {}
                },
                variant = 0
            }
        elseif info.type == 85 or info.type == 86 then
            if data == 0 then
                local addSlot = ust.mixData(ust.base(id, 56), 0)
                modules[addSlot] = {
                    metadata = {isData = true},
                    name = "station/rail/ust/data.module",
                    updateScript = {
                        fileName = "",
                        params = {}
                    },
                    variant = 0
                }
            end
        end
    end
end

local updateFn = function(result, transform, tag, slotId, addModelFn, params, closureParams)
    if params == 1 then
        return preUpdateFn(result, transform, tag, slotId, addModelFn)
    end
    local id = params.modules[slotId].info.id
    local sId = params.classedModules[id].slotId
    local info = params.modules[sId].info
    local makeData = params.modules[sId].makeData
    
    -- Entry for radius system
    local arcs = info.arcs
    local rad = (arcs.center.inf + arcs.center.sup) * 0.5
    local posL, posR = arcs.left:pt(rad), arcs.right:pt(rad)
    local vec = (posR - posL):normalized()
    local posC = (posR + posL) * 0.5
    local rotZ = quat.byVec(coor.xyz(1, 0, 0), vec):mRot()
    local transfPosC = rotZ * coor.trans(posC)
    
    table.insert(result.slots, {
        id = makeData(80, 1),
        transf = transfPosC,
        type = "ust_modifier",
        spacing = {0, 0, 0, 0}
    })
    
    local var = params.modules[params.classedModules[info.id].slot[80]].variant
    local step = (arcs.center.sup - arcs.center.inf) / 8
    
    for i = 0, 8 do
        local rad = arcs.center.inf + step * i
        local posL, posR = arcs.left:pt(rad), arcs.right:pt(rad)
        local vec = (posR - posL):normalized()
        local posC = (posR + posL) * 0.5
        local posP = posL - vec
        local posN = posR + vec
        local rotZ = quat.byVec(coor.xyz(1, 0, 0), vec):mRot()
        local textR = info.radius >= 10e8 and "R∞" or string.format("R%d(%s)", abs(info.radius), info.radius < 0 and "-" or "+")
        
        local addText = function(label, pos, fAlign, h)
            local nameModelsF, width = livetext(h or 2)(label)
            for _, m in ipairs(nameModelsF(function() return coor.trans(fAlign(width)) * coor.rotX(-0.5 * pi) * rotZ * coor.trans(pos + coor.xyz(0, 0, 3)) end)) do
                table.insert(result.models, m)
            end
        end
        
        local addSlot = function(id, data, pos, shape, rot)
            table.insert(result.slots, {
                id = makeData(id, data),
                transf = coor.scale(coor.xyz(0.75, 0.75, 0.75)) * (rot or rotZ) * coor.trans(pos),
                type = "ust_modifier",
                spacing = {0, 0, 0, 0},
                shape = shape or 0
            })
        end
        
        if (i == 0) then
            addText(textR, posC, function(w) return coor.xyz(-0.5 * w, 0, -1) end)
        elseif (i == 1) then
            addSlot(85 + var, 0, posP)
            addText("∞ ⊘", posC, function(w) return coor.xyz(-w * 0.5, 0, -1) end)
            if (params.classedModules[info.id].slot[54] or params.classedModules[info.id].slot[55] or params.classedModules[info.id].slot[56]) then
                addSlot(85 + var, 1, posN)
            end
        elseif i == 7 then
            addText("+", posP, function(w) return coor.xyz(-0.5 * w, 0, -1) end)
            addText("-", posN, function(w) return coor.xyz(-0.5 * w, 0, -1) end)
        elseif i == 8 then
            addText(textR, posC, function(w) return coor.xyz(-0.5 * w, 0, -1) end)
        else
            local delta = pow(10, i - 2)
            if info.radius >= 10e8 or (abs((info.radius or 0) + delta) >= 50 and (info.radius or 0) + delta < 999999) then
                local dir = (info.radius and info.radius < 999999 and (info.radius > 0 or (info.radius < 0 and info.radius + delta < 0))) and coor.xyz(-1, 0, 0) or coor.xyz(1, 0, 0)
                addSlot(81 + var, i - 1, posP, 1, quat.byVec(dir, vec):mRot())
            end
            if abs((info.radius or 0) - delta) >= 50 and (info.radius or 0) - delta > -999999 then
                local dir = (info.radius and info.radius < 999999 and (info.radius < 0 or (info.radius > 0 and info.radius - delta > 0))) and coor.xyz(1, 0, 0) or coor.xyz(-1, 0, 0)
                addSlot(81 + var, -i + 1, posN, 1, quat.byVec(dir, vec):mRot())
            end
            addText(string.format("∙ %d ∙", delta), posC, function(w) return coor.xyz(-w * 0.5, 0, -0.75) end, 1.5)
        end
    end
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
		visible = false,
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_RADIUS_MODIFIER"),
            description = _("MENU_RADIUS_MODIFIER_DESC"),
        },
        category = {
            categories = { "modifiers" },
        },
        type = "ust_modifier",
        order = {
            value = 260,
        },
        metadata = {
			typeName = "ust_modifier",
            isData = true,
            type = 1
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
