local coor = require "ust/coor"
local quat = require "ust/quaternion"
local ust = require "ust"

local insert = table.insert
local ma = math
local pi = ma.pi

local updateFn = function(result, transform, tag, slotId, addModelFn, params)
    local id = params.modules[slotId].info.id
    local sId = params.classedModules[id].slotId
    local info = params.modules[sId].info
    local isPlatform = params.modules[sId].metadata.isPlatform
    local refH = params.platformHeight + (info.extraHeight or 0)
    local makeData = params.modules[sId].makeData
    
    insert(result.slots, {
        id = makeData(91, 1),
        transf = info.transf * coor.transZ(refH),
        type = "ust_ref_modifier",
        spacing = {0, 0, 0, 0}
    })
    
    local n = 2
    local ptsL, vecL = ust.basePts(info.arcs.left, n)
    local ptsR, vecR = ust.basePts(info.arcs.right, n)
    local ptsC, vecC = ust.basePts(info.arcs.center, n)
    
    local addSlot = function(cond, data, transf)
        if cond then
            insert(result.slots, {
                id = makeData(92, data),
                transf = coor.scale(coor.xyz(0.125, 0.5, 1)) * coor.rotZ(-0.25 * pi) * transf * coor.transZ(refH),
                type = "ust_ref_modifier",
                spacing = {0, 0, 0, 0},
                shape = 2
            })
            
            insert(result.slots, {
                id = makeData(92, data),
                transf = coor.scale(coor.xyz(0.125, 0.5, 1)) * coor.rotZ(0.25 * pi) * transf * coor.transZ(refH),
                type = "ust_ref_modifier",
                spacing = {0, 0, 0, 0},
                shape = 2
            })
        else
            insert(result.slots, {
                id = makeData(92, data),
                transf = transf * coor.transZ(refH),
                type = "ust_ref_modifier",
                spacing = {0, 0, 0, 0},
                shape = 1
            })
        end
    end
    ust.marking(result, slotId, params)
    
    for _, octa in ipairs(info.octa) do
        if octa then
            ust.marking(result, octa, params)
        end
    end
    
    do
        local refPt = ptsL[2]
        local refVec = vecL[2]
        local transf = quat.byVec(coor.xyz(0, info.pos.y < 0 and -1 or 1, 0), refVec):mRot() * coor.trans(refPt)
        
        if info.octa[7] and params.modules[info.octa[7]] and not params.modules[info.octa[7]].info.ref.right then
            if isPlatform then
                local sum = (info.ref.right and 2 or 0) + (info.ref.left and 0 or 1)
                if (sum ~= 0) then
                    addSlot(info.ref.left, sum, transf)
                end
            elseif params.modules[info.octa[7]].metadata.isTrack then
                if info.ref.left then
                    addSlot(true, 0, transf)
                else
                    addSlot(false, 1, transf)
                end
            end
        end
    end
    
    do
        local refPt = ptsR[2]
        local refVec = vecR[2]
        local transf = quat.byVec(coor.xyz(0, info.pos.y < 0 and 1 or -1, 0), refVec):mRot() * coor.trans(refPt)
        
        if info.octa[3] and params.modules[info.octa[3]] and not params.modules[info.octa[3]].info.ref.left then
            if isPlatform then
                local sum = (info.ref.left and 1 or 0) + (info.ref.right and 0 or 2)
                if sum ~= 0 then
                    addSlot(info.ref.right, sum, transf)
                end
            elseif params.modules[info.octa[3]].metadata.isTrack then
                if info.ref.right then
                    addSlot(true, 0, transf)
                else
                    addSlot(false, 2, transf)
                end
            end
        end
    end
    
    if isPlatform then
        local i = info.pos.y < 0 and 1 or 3
        local refPt = ptsC[i]
        local refVec = vecC[i]
        local transf = quat.byVec(coor.xyz(info.pos.y < 0 and 1 or -1, 0, 0), refVec):mRot() * coor.trans(refPt)
        
        if info.octa[1] and params.modules[info.octa[1]] and not params.modules[info.octa[1]].info.ref.prev then
            if not info.ref.next then
                addSlot(info.ref.next, 4, transf)
            end
        end
    
    end
    
    if isPlatform then
        local i = info.pos.y < 0 and 3 or 1
        local refPt = ptsC[i]
        local refVec = vecC[i]
        local transf = quat.byVec(coor.xyz(info.pos.y < 0 and -1 or 1, 0, 0), refVec):mRot() * coor.trans(refPt)
        
        if info.octa[5] and params.modules[info.octa[5]] and not params.modules[info.octa[5]].info.ref.next then
            if not info.ref.prev then
                addSlot(info.ref.prev, 8, transf)
            end
        end
    end
end

function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
        visible = false,
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MENU_REF_MODIFIER"),
            description = _("MENU_REF_MODIFIER_DESC"),
        },
        category = {
            categories = {"ust_cat_modifier"},
        },
        type = "ust_ref_modifier",
        order = {
            value = 260,
        },
        metadata = {
            typeName = "ust_ref_modifier",
            isData = true,
            type = 2,
            scriptName = "construction/station/rail/ust/ref_modifier",
            preProcessAdd = "preProcessAdd",
            preProcessPostAdd = "preProcessPostAdd",
            classify = "classify"
        },
        
        updateFn = updateFn,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
