function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
		visible = false,
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = _("MODULE_REMOVE_HELPER"),
            description = _("MODULE_REMOVE_HELPER_DESC"),
        },
        category = {
            categories = {"ust_cat_track", "ust_cat_platform", "ust_cat_street"}
        },
        type = "ust_remove",
        order = {
            value = 0,
        },
        metadata = {
			typeName = "ust_remove",
            isData = true,
            scriptName = "construction/station/rail/ust/remove",
            preProcessAdd = "preProcessAdd"
        },
        
        updateFn = function() end,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
