function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
		visible = false,
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = "HIDDEN_MODULE",
            description = "NOTHING",
        },
        category = {
            categories = { "remover" },
        },
        type = "ust_remove",
        order = {
            value = 260,
        },
        metadata = {
			typeName = "ust_remove",
            isData = true
        },
        
        updateFn = function(modules, change, classedModules, info, _, fn_no)
            if fn_no.fn then
                if info.id ~= 1 then
                    for _, slotId in pairs(classedModules[info.id].slot) do
                        modules[slotId] = nil
                    end
                    modules[classedModules[info.id].slotId] = nil
                    modules[change.slotId] = nil
                end
            end
        end,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
