function data()
    return {
        preProcessAdd = function(modules, change, classedModules, info)
            if info.id ~= 1 then
                for _, slotId in pairs(classedModules[info.id].slot) do
                    modules[slotId] = nil
                end
                modules[classedModules[info.id].slotId] = nil
                modules[change.slotId] = nil
            end
        end
    }

end
