function data()
    return {
        availability = {
            yearFrom = 0,
            yearTo = 0,
        },
		visible = false,
        buildMode = "SINGLE",
        cost = {
            price = 0,
        },
        description = {
            name = "HIDDEN_MODULE",
            description = "NOTHING",
        },
        category = {
            categories = { "remover" },
        },
        type = "ust_remove",
        order = {
            value = 260,
        },
        metadata = {
			typeName = "ust_remove",
            isData = true
        },
        
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
        end,
        
        getModelsFn = function(params)
            return {}
        end
    }

end
